Updated git-graphviz.
Made it faster by removing tedious git calls; using 'join' and 'sed' more.

Made it display 'HEAD' when possible.

Made it distinguish between '1' and '2' merge parent links.

Enabled it to display annotated tags.

diff --git a/src/bin/git-graphviz b/src/bin/git-graphviz
--- a/src/bin/git-graphviz
+++ b/src/bin/git-graphviz
@@ -27,8 +27,15 @@ opt_url_at_remote () {
 #HELP:  --all | -a: show all commits & refs in the repository
 unset all
 opt_all () {
-    (( $# == 0 ))|| fail_assert "$FUNCNAME expects 0 args (got $#)"
+    (( $# == 0 )) || fail_assert "$FUNCNAME expects 0 args (got $#)"
     all=true
+}
+
+#HELP:  --decorate | -d: Decorate logs: show branches, tags, and references
+unset decorate
+opt_decorate () {
+    (( $# == 0 )) || fail_assert "$FUNCNAME expects 0 args (got $#)"
+    decorate=true
 }
 
 #HELP:  --open | -o: open the HTML result file
@@ -50,10 +57,11 @@ opt_date () {
 }
 
 OPTIND=1
-while getopts :ahkou:v-: OPTION
+while getopts :adhkou:v-: OPTION
 do
     case "$OPTION" in
         a ) opt_all;;
+        d ) opt_decorate;;
         h ) opt_help;;
         k ) opt_keep_temps;;
         o ) opt_open;;
@@ -62,6 +70,7 @@ do
         - )
             case "$OPTARG" in
                 all ) opt_all;;
+                decorate ) opt_decorate;;
                 help ) opt_help;;
                 keep-temps ) opt_keep_temps;;
                 open ) opt_open;;
@@ -85,8 +94,9 @@ shift $((OPTIND-1))
 
 # $@ is git args
 
-if [[ -n ${all+is-set} ]]
+if [[ true = ${all-false} ]]
 then set -- --full-history --all
+     decorate=true
 fi
 
 git_log=(git log)
@@ -107,6 +117,60 @@ then git remote show "$url_at_remote" > "$git_graphviz"/remote_show.txt || fail 
      fi
 fi
 
+omit_blank_lines () {
+    egrep -v '^$' || true
+}
+
+# commit objects with parent1 and parent2
+"${git_log[@]}" --format="commit %h parents %p" "$@" > "$git_graphviz"/commits-with-parents.txt
+# commits with summary description
+"${git_log[@]}" --format="commit %h summary %cN <%cE> %cd %s" "$@" > "$git_graphviz"/commits-with-summaries.txt
+
+# sorting by commit, parent1, and parent2
+sort -k 2b,2 "$git_graphviz"/commits-with-parents.txt > "$git_graphviz"/commits-with-parents.by-commit.txt
+sort -k 4b,4 "$git_graphviz"/commits-with-parents.txt > "$git_graphviz"/commits-with-parents.by-parent-1.txt
+sort -k 5b,5 "$git_graphviz"/commits-with-parents.txt > "$git_graphviz"/commits-with-parents.by-parent-2.txt
+# get parent 1 and 2 where the parent is also in the list of commits
+join -1 4 -2 2 -o 1.1,1.2,1.3,1.4 "$git_graphviz"/commits-with-parents.by-parent-1.txt "$git_graphviz"/commits-with-parents.by-commit.txt > "$git_graphviz"/parent-1-to-commit.txt
+join -1 5 -2 2 -o 1.1,1.2,1.3,1.5 "$git_graphviz"/commits-with-parents.by-parent-2.txt "$git_graphviz"/commits-with-parents.by-commit.txt > "$git_graphviz"/parent-2-to-commit.txt
+
+if [[ true = ${decorate-false} ]]
+then
+  # decoration-style refs
+  # "${git_log[@]}" --format="object %h refs %D" "$@" > "$git_graphviz"/refs.txt
+  # tags, each tag object with name and what it references
+  git for-each-ref --format="%(if:equals=tag)%(objecttype)%(then)tag %(objectname:short) name %(refname:short) references %(*objectname:short)%(end)" refs/tags | omit_blank_lines > "$git_graphviz"/tags.txt
+  git for-each-ref --format="%(if:equals=commit)%(objecttype)%(then)name %(refname:short) references %(objectname:short)%(end)" refs/tags | omit_blank_lines > "$git_graphviz"/lightweight-tags.txt
+  git for-each-ref --format="%(if:equals=commit)%(objecttype)%(then)name %(refname:short) references %(objectname:short)%(end)" refs/heads refs/remotes | omit_blank_lines > "$git_graphviz"/references.txt
+  git rev-parse --abbrev-ref HEAD > "$git_graphviz"/head.txt
+
+  #############################################################################
+  # pick references (branches & remotes)
+  # sort references by referenced commit
+  sort -k 4b,4 "$git_graphviz"/references.txt > "$git_graphviz"/references.by-referenced-commit.txt
+  # join references to referenced commits
+  join -1 4 -2 2 -o 1.1,1.2,1.3,1.4 "$git_graphviz"/references.by-referenced-commit.txt "$git_graphviz"/commits-with-parents.by-commit.txt > "$git_graphviz"/reference-to-commit.txt
+
+  #############################################################################
+  # pick tags
+  sort -k 6b,6 "$git_graphviz"/tags.txt > "$git_graphviz"/tags.by-referenced-commit.txt
+  # join tags to referenced commits
+  join -1 6 -2 2 -o 1.1,1.2,1.3,1.4,1.5,1.6 "$git_graphviz"/tags.by-referenced-commit.txt "$git_graphviz"/commits-with-parents.by-commit.txt > "$git_graphviz"/tag-to-commit.txt
+
+  #############################################################################
+  # pick lightweight tags
+  sort -k 4b,4 "$git_graphviz"/lightweight-tags.txt > "$git_graphviz"/lightweight-tags.by-referenced-commit.txt
+  # join tags to referenced commits
+  join -1 4 -2 2 -o 1.1,1.2,1.3,1.4 "$git_graphviz"/lightweight-tags.by-referenced-commit.txt "$git_graphviz"/commits-with-parents.by-commit.txt > "$git_graphviz"/lightweight-tag-to-commit.txt
+
+  #############################################################################
+  # pick HEAD
+  sort -k 2b,2 "$git_graphviz"/reference-to-commit.txt > "$git_graphviz"/reference-to-commit.by-name.txt
+  # join tags to referenced commits
+  join -1 1 -2 2 -o 2.1,2.2 "$git_graphviz"/head.txt "$git_graphviz"/reference-to-commit.by-name.txt > "$git_graphviz"/head-to-reference.txt
+
+fi
+
 {
     cat <<EOF
 digraph git_graph {
@@ -114,52 +178,29 @@ digraph git_graph {
     node [fontname = "Helvetica", fontsize = 10, width = 0, height = 0, shape=box, style=rounded];
 EOF
 
-    {
-        "${git_log[@]}" --pretty="format:%h %cN <%cE> %cd %s" "$@"
-        printf '\n'
-    } > "$git_graphviz"/commits.txt
+    sed -e 's/"/\\"/g' -e 's/commit \([^ ]*\) summary \(.*\)$/"\1" [id="id_\1", tooltip="\2"];/' "$git_graphviz"/commits-with-summaries.txt
+    sed -e 's/commit \([^ ]*\) parents \(.*\)$/"\1" -> "\2";/' "$git_graphviz"/parent-1-to-commit.txt
+    sed -e 's/commit \([^ ]*\) parents \(.*\)$/"\1" -> "\2" [taillabel="2"];/' "$git_graphviz"/parent-2-to-commit.txt
 
-    while read -d$'\n' short summary
-    do summary1=${summary//\"/\\\"}
-       url=$("${git_log[@]}" --pretty="$url_format" -n 1 "$short")
-       printf '"%s" [id="id_%s", tooltip="%s", URL="%s"];\n' "$short" "$short" "$summary1" "$url"
-    done < "$git_graphviz"/commits.txt
+    if [[ true = ${decorate-false} ]]
+    then
 
-    put_parents() {
-        from=$1
-        shift
-        while (( $# > 0 ))
-        do # exclude commits not in the list
-            if egrep -q "^$1" "$git_graphviz"/commits.txt 
-            then printf '"%s" -> "%s";\n' "$from" "$1" 
-            fi
-            shift
-        done
-    }
-
-    while read -d$'\n' -a parents
-    do put_parents "${parents[@]}"
-    done < <("${git_log[@]}" --pretty='%h %p' "$@")
-
-    cat <<EOF
+      cat <<EOF
     node [shape=plaintext];
 EOF
 
-    if [[ -n ${all+is-set} ]]
-    then
-      git for-each-ref --format="\"%(refname:short)\" -> \"%(objectname:short)\";" refs/heads refs/remotes
-      git for-each-ref --format="\"tag:%(refname:short)\" -> \"%(objectname:short)\";" refs/tags
-    else
-        git for-each-ref --format='%(objectname:short) %(refname:short)' refs/heads refs/remotes > "$git_graphviz"/refs.txt
-        for commit in $("${git_log[@]}" --format="format:%h" "$@")
-        do # print the tags
-           for tag in $(git tag -l --points-at $commit)
-           do printf "\"tag:%s\" -> \"%s\";\n" $tag $commit
-           done
-           # print heads & remotes
-           egrep "^$commit" "$git_graphviz"/refs.txt \
-             | sed -e 's/^\([^ ]*\) \(.*$\)/"\2" -> "\1";/'
-        done
+      sed -e 's/name \([^ ]*\) references \(.*\)$/"tag:\1" -> "\2";/' "$git_graphviz"/lightweight-tag-to-commit.txt
+      sed -e 's/name \([^ ]*\) references \(.*\)$/"\1" -> "\2";/' "$git_graphviz"/reference-to-commit.txt
+
+
+      cat <<EOF
+    node [shape=box, style=solid];
+EOF
+
+      sed -e 's/tag \([^ ]*\) name \([^ ]*\) references \(.*\)$/"\1" [label="\2"];"\1" -> "\3";/' "$git_graphviz"/tag-to-commit.txt
+
+      sed -e 's/name \(.*\)$/"HEAD" [shape=plain];"HEAD" -> "\1";/' "$git_graphviz"/head-to-reference.txt
+
     fi
     
     cat <<EOF
