Updated git-graphviz to link to commits in repos.
Close issue https://github.com/webb/wrtools-git/issues/2.

Updated remote URL command line paramter to --remote $remote or -r $remote

Reworked the way remote urls tooltip & commit node generation works.

diff --git a/src/bin/git-graphviz b/src/bin/git-graphviz
--- a/src/bin/git-graphviz
+++ b/src/bin/git-graphviz
@@ -15,13 +15,13 @@ root_dir=$(dirname "$0")/..
 . "$root_dir"/share/wrtools-core/fail.bash
 . "$root_dir"/share/wrtools-core/temp.bash
 
-#HELP:  --url-at-remote=$remote-name | -u $remote-name: point commits to URLs based on
-#HELP:                                                  a remote repo
-unset url_at_remote
-opt_url_at_remote () {
+#HELP:  --remote=$remote-name | -r $remote-name: point commits to URLs based on
+#HELP:                                           a remote repo
+unset remote
+opt_remote () {
     (( $# == 1 ))|| fail_assert "$FUNCNAME expects 1 arg, a remote name"
-    [[ -z ${url_at_remote+is-set} ]] || fail "$Option --url-at-remote can only be used once"
-    url_at_remote=$1
+    [[ is-set != ${remote+is-set} ]] || fail "Option --remote can only be used once"
+    remote=$1
 }
 
 #HELP:  --all | -a: show all commits & refs in the repository
@@ -57,7 +57,7 @@ opt_date () {
 }
 
 OPTIND=1
-while getopts :adhkou:v-: OPTION
+while getopts :adhkor:v-: OPTION
 do
     case "$OPTION" in
         a ) opt_all;;
@@ -65,7 +65,7 @@ do
         h ) opt_help;;
         k ) opt_keep_temps;;
         o ) opt_open;;
-        u ) opt_url_at_remote "$OPTARG";;
+        r ) opt_remote "$OPTARG";;
         v ) opt_verbose;;
         - )
             case "$OPTARG" in
@@ -79,10 +79,8 @@ do
                     fail "No argument expected for long option \"${OPTARG%%=*}\"";;
 
                 date=* ) opt_date "${OPTARG#*=}";;
-                url-at-remote=* ) opt_url_at_remote "${OPTARG#*=}";;
-                url-at-remote | date )
-                    fail "Missing required argument for long option \"$OPTARG\"";;
-                
+                remote ) fail "Long option \"$OPTARG\" missing argument";;
+                remote=* ) opt_remote "${OPTARG#*=}";;
                 * ) fail "Unexpected long option \"$OPTARG\"";;
             esac;;
         '?' ) fail "Unknown short option \"$OPTARG\"";;
@@ -92,7 +90,7 @@ do
 done
 shift $((OPTIND-1))
 
-# $@ is git args
+# $@ is git log args
 
 if [[ true = ${all-false} ]]
 then set -- --full-history --all
@@ -106,25 +104,39 @@ fi
 
 temp_make_dir git_graphviz
 
-url_format="format:%H"
-if [[ -n ${url_at_remote+is-set} ]]
-then git remote show "$url_at_remote" > "$git_graphviz"/remote_show.txt || fail "Remote $url_at_remote not found"
-     sed -e 's/^  Fetch URL: \(.*\)$/\1/p;d' < "$git_graphviz"/remote_show.txt > "$git_graphviz"/remote_url.txt
-     remote_url=$(cat "$git_graphviz"/remote_url.txt)
-     if [[ $remote_url == https://github.com/* ]]
-     then printf -v url_format "%s/commit/%%H" "${remote_url%.git}"
-     else fail "I don't know how to render remote $remote_url"
-     fi
+if [[ is-set = ${remote+is-set} ]]
+then true
+elif remote=$(git config --get-regexp '^remote.[^.]*.url$' | sed -e '1s/^remote\.\([^\.]*\).url .*$/\1/p;d')
+then true
 fi
+vecho "remote is ${remote-unset}"
 
-omit_blank_lines () {
-    egrep -v '^$' || true
-}
+unset remote_url
+if remote_url=$(git config --get "remote.$remote.url")
+then true
+fi
+vecho "remote_url is ${remote_url-unset}"
 
+case ${remote_url-} in
+    https://github.com/* )
+        use_remote_url=${remote_url%.git}
+        # params: $1 = short hash; $2 = long hash; $3 = summary
+        render_node () {
+            printf "\"%s\" [tooltip=\"%s\",URL=\"$use_remote_url/commit/%s\"]\n" "$1" "$3" "$2"
+        }
+        ;;
+    * )
+        render_node () {
+            printf "\"%s\" [tooltip=\"%s\",]\n" "$1" "$3"
+        }
+        ;;
+esac
+   
 # commit objects with parent1 and parent2
 "${git_log[@]}" --format="commit %h parents %p" "$@" > "$git_graphviz"/commits-with-parents.txt
 # commits with summary description
-"${git_log[@]}" --format="commit %h summary %cN <%cE> %cd %s" "$@" > "$git_graphviz"/commits-with-summaries.txt
+# commit $commit-abbrev long $commit-long summary $summary
+"${git_log[@]}" --format="commit %h long %H summary %cN <%cE> %cd %s" "$@" | sed -e 's/"/\\\\"/g' > "$git_graphviz"/commits-with-summaries.txt
 # all hashes in the graph, sorted
 cut -d ' ' -f 2 < "$git_graphviz"/commits-with-parents.txt | sort -b > "$git_graphviz"/hashes.txt
 
@@ -206,7 +218,11 @@ digraph git_graph {
     node [fontname = "Helvetica", fontsize = 10, width = 0, height = 0, shape=box, style=rounded];
 EOF
 
-    sed -e 's/"/\\"/g' -e 's/commit \([^ ]*\) summary \(.*\)$/"\1" [id="id_\1", tooltip="\2"];/' "$git_graphviz"/commits-with-summaries.txt
+    # commit $commit-abbrev long $commit-long summary $summary...
+    while read L1 commit_abbrev L2 commit_long L3 summary
+    do render_node "$commit_abbrev" "$commit_long" "$summary"
+    done < "$git_graphviz"/commits-with-summaries.txt
+    
     sed -e 's/commit \([^ ]*\) parents \(.*\)$/"\1" -> "\2";/' "$git_graphviz"/parent-1-to-commit.txt
     sed -e 's/commit \([^ ]*\) parents \(.*\)$/"\1" -> "\2" [taillabel="2"];/' "$git_graphviz"/parent-2-to-commit.txt
 
